### ISSUE TITLE
Femtocleaner doesn't look like it's branching from master

### ISSUE THREAD

**Issue by mkborregaard** [JuliaComputing/FemtoCleaner.jl#34] opened 2017-08-23 09:59 UTC
I disagree with some changes made by femtocleaner, and went on to edit the fp/deps branch manually. But looking at the git tree, it doesn't look like it's branched from master. Should I rebase?

My git tree (in GitKraken):
![skaermbillede 2017-08-23 kl 11 50 47](https://user-images.githubusercontent.com/8429802/29610373-4ae2793e-87fa-11e7-977e-bfaec27327c6.png)

**Comment by mkborregaard** [comment] 2017-08-23 09:59
"3 hours ago is also wrong"

**Comment by Keno** [comment] 2017-08-24 19:20
Hmm, you're right, the commit seems to be missing a parent reference. I'll take a look.

**Comment by Keno** [comment] 2017-08-24 22:48
I pushed a commit, which might have helped. However, looking back at this, I can't actually reproduce the problem. The reason I thought I could reproduce this originally was because github doesn't show the "parent" field in its UI, but by looking at the raw commit in the repo it is actually there. To be sure, I then downloaded GitKraken and opened up a bunch of other repos and I can't reproduce the behavior either (even on repos before the patch). Same with JuliaPlots for me. So I'm gonna close this as "can't reproduce". If you encounter this again and have steps to reproduce, please let me know.

**Closed by Keno** 2017-08-24 22:48 UTC

**Comment by mkborregaard** [comment] 2017-08-25 06:07
Indeed your commit helped, it now branches off correctly. Not sure what caused this, I didn't tamper with the branch - but it is possible we merged a PR just while the bot was working. Not sure if that was the issue. Thanks for looking into this!
